##########################################
############   Routes APP   ##############
##########################################
app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_ticket:
    resource: "@AppBundle/Resources/config/routing/ticket.yml"
    prefix:   /ticket

##########################################
############   Routes Search   ###########
##########################################

searchController:
    path:     /search
    defaults: { _controller: SearchBundle:SearchEngine:search }
    methods:  [GET, POST]

##########################################
###########   Routes ADMIN   #############
##########################################

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

###################################################################################################################