ticket_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Ticket:show" }
    methods:  GET

ticket_new:
    path:     /new
    defaults: { _controller: "AppBundle:Ticket:new" }
    methods:  [GET, POST]
