
AppBundle\Entity\Ticket:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\TicketRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    society:
      type: string
      length: 60
      nullable: false
#    user_name:
#      type: string
#      length: 100
#      nullable: false
    phone:
      type: string
      lengh: 15
#    email:
#      type: string
#      length: 255
    comment:
      type: text
    date:
      type: date
    ip_address:
      type: string
      length: 30
    treated:
      type: boolean
      nullable: true

  manyToOne:
      user:
          targetEntity: AdminBundle\Entity\User
          inversedBy: ticket
          joinColumn:
              name: user_id
              referencedColumnName: id

  lifecycleCallbacks: {  }