CalendarBundle\Entity\Calendar:
    type: entity
    table: null
    repositoryClass: CalendarBundle\Repository\AgendaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        start:
            type: datetime
        end:
            type: datetime
        society:
            type: string
            length: 60
            nullable: false
        user_name:
            type: string
            length: 100
            nullable: false
        phone:
            type: string
            lengh: 1
        email:
            type: string
            length: 255
        comment:
            type: text

    lifecycleCallbacks: {  }
